### ISSUE TITLE
Query regarding methodology

### ISSUE THREAD

**Issue by ankitpatnala** [staffik/bigan_mnist#1]
Why don't you train discriminator ? paper suggests to train simultaneously right ?

**Comment by staffik** [comment]
I train the discriminator.
Note that I set `trainable=False` after `D.compile()`.
The reason is that we want to fix the discriminator part in the full setup.
See section `Training` of https://towardsdatascience.com/comprehensive-introduction-to-turing-learning-and-gans-part-2-fd8e4a70775
